### ISSUE TITLE
Javadoc is broken

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#1275]
Dozens of modules are failing on `javadoc:javadoc` goal. Causes need to be fixed and `javadoc:javadoc` should be attached to the `verify` phase.

**Comment by lukaszspyra** [comment]
Hi,

I have done some checks on modules currently used for HTML javadoc (according to pom.xml, `log4j-api` and `log4j-core`). Different maven plugin options for javadoc [doclet](https://docs.oracle.com/en/java/javase/11/docs/specs/doc-comment-spec.html,) resulted in:

1) for doclet turned off: 24 warnings (mostly referenes not found, wrong param names)

2) for doclet fully on: 200 warnings,119 errors (all kinds of html tags not supported in HTML5, missing closing tags, empty <p> tags,  missing docs on public members e.g. on getters (whilst most of them are self explanatory) - very strict approach

3) for doclet [partly off](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javadoc.html#additional-options-provided-by-the-standard-doclet) (ignores missing docs and high-level HTML issues): around 40 errors / 60 warnings

What would be the recommended approach for fixing javadoc? 
I'd say at least excluding missing docs, and maybe html strict semantics (otherwise some tags would have to be replaced by external .css as not supported in HTML5 - e.g. `align` in table cells)?

**Comment by vy** [comment]
I would be in favor of a spotless `javadoc:javadoc` run. Though it all depends on how far you want to push.

(@lukaszspyra, PMC really appreciates your recent interest and work on the project. :heart_eyes: Keep up the great job! :100:)

**Comment by lukaszspyra** [comment]
Hi,
Corrected some javadocs with PR #1753.
There are still many failures remaining, but first need to figure out best way how to fix links to docs in modules, which are excluded from javadoc creation.

**Comment by vy** [comment]
Thanks to hard work of @lukaszspyra in #1753, the situation is improved.
