### ISSUE TITLE
2.20 did not get published to Maven central repository

### ISSUE THREAD

**Issue by xzel23** [apache/logging-log4j2#1282]
## Description

Version 2.20 was released four days days ago, and documentation gives Maven coordinates for version 2.20. However the newest version available on Maven central repository is still 2.19.

## Configuration

**Version:** 2.20

## Reproduction

Check available version for log4j on [Maven Central Repository](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api).

**Comment by ppkarwasz** [comment]
@xzel23,

Releasing an Apache project is a long process; version 2.20.0 hasn't been officially released yet:

 * the voting procedure began on February 18th UTC: https://lists.apache.org/thread/l3ftyl9r2cfsp49dksdvddv12pfhtskt
 * on February 21st UTC the vote passed: https://lists.apache.org/thread/xw7k9prf22vx5dsjk0xtdnsf1y3hdsz5

The release process ends with an announcement mail on the [`dev@logging.apache.org`](https://lists.apache.org/list.html?dev@logging.apache.org) list.

**Comment by xzel23** [comment]
OK, thank you. So the website and downloads page are a bit ahead of events. When you just open the [project page](https://logging.apache.org/) right below the logo the text "Last Published: 2023-02-17|  Version: 2.20.0" is displayed and the downloads also already show the 2.20 version. I assumed the "Last Published" meant released.

**Comment by ppkarwasz** [comment]
@xzel23,

The dates are generated together with the static website. I guess the same is true for those on Maven Central (you can [find them on Sonatype](https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-api/2.20.0/)), but I don't know how Sonatype Nexus Manager deals with dates.

If you have an idea how to modify our Maven config to use dates 72 hours in the future, feel free to reopen this issue.

**Comment by rgoers** [comment]
Normally, Maven Central is updated within a few hours. dist.apache.org normally takes many hours to sync with all its mirrors. Our policy is to not publish the release announcement for 24 hours after the artifacts are published due to these delays.  

Note that the release build ran on Feb 17, but the release process requires 72 hours (3 days) at a minimum for PMC members to approve the release. So generally, the artifacts are available 3.5 to 4 days after the release vote email goes out.
