### ISSUE TITLE
Spotless failures should generate artifacts

### ISSUE THREAD

**Issue by jsoref** [apache/logging-log4j2#1319]
When spotless fails, all of the files it wants to change and the diffs it produces should be uploaded as artifacts using `actions/upload-artifact` so that contributors (especially drive-by) can see the things that it doesn't like and apply them directly without having to go through 50 iterations to get to a satisfactory state.

**Comment by ppkarwasz** [comment]
Since `./mvnw spotless:apply` is a simple fix to formatting problems and it is mentioned in the error message, I don't see the need for a sophisticated formatting mechanism.

**Comment by jsoref** [comment]
A quick skim shows that this repository refuses to build with anything other than java 11:
https://github.com/apache/logging-log4j2/blob/59275a93429ff5a2073aee507c3c3c07da3825cd/pom.xml#L315

Java 11 reached EOL in September and my employer just replaced Java 11 with Java 21.

My computer's default version of java is 21. It's true that I still have a couple of jdk11s installed, but I should garbage collect them.

When playing in the GitHub ecosystem, it's really nice to drive-by contributors if your CI cycles provide outputs for things you've already spent gobs of cycles on so that others don't have to waste their time regenerating them. This is one of those things. And trust me, I spent *gobs* of time trying to get the spelling PR ready for this repository banging my head against spotless.

Not to point fingers, but your responses to my requests have been incredibly counterproductive. I asked a simple question based on the fact that I had seriously tried and failed to get things to work and you gave a response that didn't work:
https://github.com/apache/logging-log4j2/pull/613#issuecomment-1449476254

I'm asking for something simple for which I'm very willing (and able!) to provide an implementation.

Anyway, I've wasted quite a bit of time on this repository, so when someone is open to assisting me in contributing, I'm available to contribute, until then, I'm writing this repository off.

**Comment by ppkarwasz** [comment]
@jsoref,

Yes, we are aware of the Java 11 limitation (cf. #1851). The only reason it is in place is because some tests are failing with JDK 17 (and even more with JDK 21).

Remark that due to your comments:

- we have fixed Spotless so that it works with every module (including `log4j-bom`, which didn't have a Spotless configuration),
- we have formatted the entire source code using it, so that contributors are not asked to reformat code they did not modify,
- recently we reformatted everything again with a deterministic formatter ([palantir-java-format](https://github.com/palantir/palantir-java-format)).

So I wouldn't say you wasted your time writing those comments.
