### ISSUE TITLE
Replace `synchronized` blocks with locks for performance in virtual threads

### ISSUE THREAD

**Issue by kelemen** [apache/logging-log4j2#1532]
Log4j ~uses~ might be using `synchronized` blocks on certain hot paths, e.g., `RollingFileManager`. This might cause performance degradation when such code runs in a virtual thread, since `synchronized` blocks pin the carrier thread and undermine the whole non-blocking nature promised by virtual threads. To avoid this one can replace `synchronized` blocks with atomic components, locks, etc.

This ticket aims to find such `synchronized` usages and replace them with more virtual-thread-friendly constructs.

**Comment by vy** [comment]
This – replacing `synchronized` blocks with locks to comply with virtual threads proposed by JEP 425, in particular, at hot spots – is indeed a known limitation that is still yet to be worked out. There is also [LOG4J2-3622](https://issues.apache.org/jira/browse/LOG4J2-3622) dealing with the `disableThreadLocals` kill-switch issue.

**Comment by kelemen** [comment]
There is no such "kill-switch" anymore (in 21). So, I guess that is one problem solved :)

**Comment by vy** [comment]
@kelemen, thanks for tip! I have updated [LOG4J2-3622](https://issues.apache.org/jira/browse/LOG4J2-3622) with the information you shared, and closed it. It is good to keep this ticket around for the `synchronized`-to-lock effort. I have updated the description of this ticket accordingly too.

**Comment by jvz** [comment]
I've updated most of the usages (at least in API and Core). There's a little bit left to do to migrate the rest, but this is largely complete.

**Comment by agentgt** [comment]
Hey guys I have been working on my own SLF4J adapter that is for Java 21. I was benchmarking against log4j2 and logback noticed when I load up like 10,000 vthreads log4j2 crushes in these scenarios (about half the time) and appears because it pins the threads and thus a single writer scenario happens (which is fast).

I made sure this was the case as I disabled ThreadLocals and set garbage collection to epsilon etc (e.g. no gc).

However the benchmark is flawed because:

* I'm only testing System.out piped to a file
* The only IO that is happening is obviously logging

The code seems to be in `OutputStreamManager` which I'm sure @jvz is aware of:

```
        synchronized (this) {
          ByteBufferDestinationHelper.writeToUnsynchronized(data, this);
        }
```

As soon as I did similar my library performed similar to log4j2.

I'm just letting you know because there maybe some that actually want the above behavior (e.g. pinning the thread)!

I'm trying to decide how to construct a more realistic test of virtual threads hitting other IO like a database and then logging to how bad `synchronized` is for log4j2.

**Comment by jvz** [comment]
Yeah, you can see that updated in https://github.com/apache/logging-log4j2/commit/9d102de78f9f4b4c8ac03b428a952c77039bb73a#diff-734786443edbd8c3b84ca999ecbf69a160ce730ac68eaedbf5f593955242142b where `synchronized` is replaced with use of the `ReentrantLock` from its parent class in https://github.com/apache/logging-log4j2/commit/9d102de78f9f4b4c8ac03b428a952c77039bb73a#diff-a0c89b2147b519600e9faf94a28d0a9a9817b59ea98bb0b940b6d03191446d4a

Pinning a thread for log output is one of the exact use cases for using asynchronous loggers so that appenders get pinned to that async thread.

**Comment by zekronium** [comment]
Any possibility of backporting this to 2.x?

**Comment by vy** [comment]
I don't think this issue will be relevant anymore after Java 23, see [this heads-up notice from the OpenJDK team addressing pinning issues in `synchronized`](https://inside.java/2024/06/22/quality-heads-up/).

**Comment by kelemen** [comment]
It will still be somewhat relevant, because object monitors are expected to remain less performant on VT (see Ron's comment on <https://mail.openjdk.org/pipermail/loom-dev/2024-July/006885.html>). That said, it probably won't be critical enough to warrant a backport.

**Comment by zekronium** [comment]
When is the planned release of log4j3. If its faster than the next LTS, then it wont matter anyway

**Comment by vy** [comment]
> It will still be somewhat relevant, because object monitors are expected to remain less performant on VT (see Ron's comment on https://mail.openjdk.org/pipermail/loom-dev/2024-July/006885.html). That said, it probably won't be critical enough to warrant a backport.

@kelemen, that is a very interesting detail. Thanks for pointing it out! :bow: I will consult to `loom-dev@` for details and update this if needed.

For the record, I created #2725 to replace monitors with locks in Log4j 2. I will be working on it...

> When is the planned release of log4j3?

@zekronium, every maintainer has a different opinion about it, mine is: I don't see it happening this year.

**Comment by zekronium** [comment]
@vy Thank you for opening the issue, maybe this would help it land sooner than version 3. The places where I encountered pinning are all fixed in 3 so I hope its easy to port over
