### ISSUE TITLE
Log4j2 json int values

### ISSUE THREAD

**Issue by saraitcheikh** [apache/logging-log4j2#1556]
Hello, 
We have been trying to jsonify logs on our scala application for operational purposes, the approach we took initially is apply a json template on our log entries using the log4j-layout-template-json library and resolving values through mdc resolver:
log4j2.xml: 
  <Console name="JsonConsoleAppender" target="SYSTEM_OUT">
            <JsonTemplateLayout eventTemplateUri="file:log_template.json"/>
        </Console >
log_template.json:
{ "count":{
    "$resolver": "mdc",
    "key": "count"
  }
}
We valorize our fields using threadContext.put which is a Map(String,String)
The issue we are facing is that we would like to convert some of our field from string to int/long since we initialize them as string using the threadContext.put, we have tried several solutions to no avail.
Has anyone faced this issue before? Or know how to resolve it
Thanks in advance for your replies 
Regards

**Comment by vy** [comment]
As clearly stated in [our support policy](https://logging.apache.org/log4j/2.x/support.html), please **don't use GitHub Issues for questions**.

`ThreadContext` doesn't allow non-`String` values. The issue was already raised in [LOG4J2-1648](https://issues.apache.org/jira/browse/LOG4J2-1648). Judging from my personal experience, non-`String` MDC values is, most of the time, a bad idea. If you are certain about your use case, I strongly recommend you to share this in the `log4j-user@logging.apache.org` mailing list.
