### ISSUE TITLE
[MS3] Modernization #1

### ISSUE THREAD

**Issue by grobmeier** [apache/logging-log4j2#1705]
- [x] #1830
- [x] Upgrade Core dependencies

**Comment by ppkarwasz** [comment]
#1819 is part of this milestone.

**Comment by ppkarwasz** [comment]
Dependencies are managed by Dependabot, with a Github Action that automatically merges them if the build is successful.

Since the branch `release/2.21.0` these upgrades were accepted for the next release:
 - #1796,
 - #1797,
 - #1802,
 - #1808,
 - #1810,
 - #1816,
 - #1824,
 - #1837,
 - #1839,
 - #1847.
