### ISSUE TITLE
[MS4] Modernization #2

### ISSUE THREAD

**Issue by grobmeier** [apache/logging-log4j2#1706]
We need to add some code formatting standards and address issues detected by multiple static analysis tools:

Code formatting standards can be addressed by:
- [x] Spotless

Regarding static analysis we plan to:
- [x] #1849 
- [x] #1850
- [x] solve [Dependabot alerts](https://github.com/apache/logging-log4j2/security/dependabot) as soon as possible,
- [x] solve problems detected by [CodeQL](https://github.com/apache/logging-log4j2/security/code-scanning/tools/CodeQL/status),
- [x] solve problems detected by [Scorecard](https://github.com/apache/logging-log4j2/security/code-scanning/tools/Scorecard/status).

**Comment by ppkarwasz** [comment]
Reports by the three tools integrated into Github (Dependabot, CodeQL, Scorecard) have been addressed.

We can not achieve the [CII-Best-Practices](https://github.com/apache/logging-log4j2/security/code-scanning/10) badge, until we introduce a **dynamic** analysis tool (fuzzing).

**Comment by ppkarwasz** [comment]
Commits related to this issue:

- da836b16d6daf87fac7ca80a5123150fb92669f3

**Comment by ppkarwasz** [comment]
We introduced a deterministic formatter in apache/logging-parent#59.

The process of choosing the right formatter started on September 20th in [this `dev` thread](https://lists.apache.org/thread/t2fxkk4cx6x70wx8m1ld0n75nq39j62f). The choice fell on [palantir-java-format](https://github.com/palantir/palantir-java-format), because:

- it has an excellent Java 8 (lambdas) support (compared to [google-java-format](https://github.com/google/google-java-format)),
- it is largely compatible with our [previous Java Style Guide](https://logging.apache.org/log4j/2.x/javastyle.html). Compared to the Google Java Format, it uses an indentation of **4** spaces instead of **2** spaces,
- compared to the [Eclipse Java formatter](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fpreferences%2Fjava%2Fcodestyle%2Fref-preferences-formatter.htm) it has no formatting options. This is actually an advantage, since it prevents discussing each one of the hundreds Eclipse options. Moreover some Eclipse options render the formatting non-deterministic,
- it provides support for both our build environment (Spotless) and IntelliJ IDEA editor,

In order to provide support for the Eclipse IDE, we ported Google's Java Format Eclipse plugin to `palantir-java-format`: palantir/palantir-java-format#949.
