### ISSUE TITLE
last minute's last log will be stored in next minute's folder

### ISSUE THREAD

**Issue by Guohaonan1** [apache/logging-log4j2#1722]
As clearly indicated in [the Log4j support page](https://logging.apache.org/log4j/2.x/support.html#issues), **please use mailing lists for questions!**

Issues asking questions will be removed, and you will be asked to post questions to the mailing lists instead.

**Comment by Guohaonan1** [comment]
in  springboot2.4.2 + log4j2 2.13.3, it's correct

in  springboot3.1.2 + log4j2 2.20

for example, every minute use a folder to store the log, xml file like that
```   
        <RollingFile name="dataRollingFile" fileName="${FILE_PATH}/${APPLICATION_NAME}-info.log"
                     filePattern="${FILE_PATH}/$${date:yyyy-MM-dd-HH-mm}/info-%d{yyyy-MM-dd-HH-mm}-%i.log">
            <PatternLayout
                    pattern="[%d{yyyy-MM-dd HH:mm:ss}] %-5level %class{36} %L %M - %msg%xEx%n"/>
            <Policies>
                <SizeBasedTriggeringPolicy size="1KB"/>
                <CronTriggeringPolicy schedule="1 * * * * ?" evaluateOnStartup="true" />
<!--                <TimeBasedTriggeringPolicy interval="1"/>-->
            </Policies>
        </RollingFile>
```

the result  folder tree like that:
```
├── 2023-08-22-16-45
│   └── info-2023-08-22-16-44-1.log
├── 2023-08-22-16-46
│   └── info-2023-08-22-16-45-1.log
├── 2023-08-22-16-47
│   └── info-2023-08-22-16-46-1.log
├── 2023-08-22-16-48
├── 2023-08-22-16-49
```

last minute's last log will be stored in next minute's folder, how to fix it

**Comment by ppkarwasz** [comment]
@Guohaonan1,

As clearly indicated in [the Log4j support page](https://logging.apache.org/log4j/2.x/support.html#issues) and your first message, please use `log4j-user` to post questions (cf. [support page](https://logging.apache.org/log4j/2.x/support.html)).

Alternatively you can post it on [StackOverflow](https://stackoverflow.com/questions/tagged/log4j2) and add the `[log4j2]` tag.

**Comment by rgoers** [comment]
Despite this having been closed I am going to provide an explanation.

1. Despite your using CronTriggeringPolicy the %d pattern is used to calculate the rollover interval for the purposes of calculating the file name. It does this by using the file creation time of the log file. This is so the file always has a time that is the same or earlier than the first log record in the file.
2. The $date lookup uses the current time of when the lookup is invoked. 

I would suggest you try using %d for your directory name and then only include %i in the file name. This actually makes more sense since, with what you wanted, the time in the directory and time in the file name would always be the same.

**Comment by ppkarwasz** [comment]
> I would suggest you try using %d for your directory name and then only include %i in the file name. This actually makes more sense since, with what you wanted, the time in the directory and time in the file name would always be the same.

Looking at the current code of [`PatternProcessor`](https://github.com/apache/logging-log4j2/blob/cec4730c56d77b22c5b147af5bacfc98ba3124e7/log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/PatternProcessor.java#L91), using two `%d` patterns should work too.
