### ISSUE TITLE
Use the release process on secondary repositories

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#1774]
The common release process from issue #1772  needs to be deployed on our secondary repositories:

 - [ ] https://github.com/apache/logging-parent,
 - [ ] https://github.com/apache/logging-log4j-tools,
 - [ ] https://github.com/apache/logging-log4j-transform,
 - [ ] https://github.com/apache/logging-log4j-kotlin,
 - [ ] https://github.com/apache/logging-log4j-jmx-gui,
 - [ ] https://github.com/apache/logging-log4j-audit,
 - [ ] https://github.com/apache/logging-log4j-server,

Some parts can also apply to the repositories:

 - [ ] https://github.com/apache/logging-log4j-audit-sample,
 - [ ] https://github.com/apache/logging-log4j-scala,
 - [ ] https://github.com/apache/logging-log4j-samples.

These repos have not seen activity in many years, should not be migrated, but possibly can be archived:
 - [ ] https://github.com/apache/logging-log4j-boot,
 - [ ] https://github.com/apache/logging-log4j-plugins.

**Comment by vy** [comment]
## Repositories migrated to the new release process

`logging-parent` version `10.0.0` release (addressing #1772) introduces great Maven (i.e., build) and GitHub Actions (i.e., CI pipeline) convenience. The following repositories were updated to take advantage of this:

- [logging-parent](/apache/logging-parent) – Yes! `logging-parent` is using itself for releases too!
- [logging-log4j-tools](/apache/logging-log4j-tools)
- [logging-log4j-transform](/apache/logging-log4j-transform)
- [logging-log4j-kotlin](/apache/logging-log4j-kotlin)
- [logging-log4j-jmx-gui](/apache/logging-log4j-jmx-gui) – introduced as a part of #1773
- [logging-log4j-samples](/apache/logging-log4j-samples)

## Repositories archived

The following repositories are archived to make it clear that they are not maintained anymore.

- [log4j](/apache/log4j)
- [log4j-receivers](/apache/log4j-receivers)
- [log4j-extras](/apache/log4j-extras)
- [log4j-components](/apache/log4j-components)
- [log4j-zeroconf](/apache/log4j-zeroconf)
- [logging-pipelines](/apache/logging-pipelines)
- [logging-log4j-boot](/apache/logging-log4j-boot)

## Repositories deleted

The following repositories were deleted since they are effectively empty.

- [log4j-plugins](/apache/log4j-plugins)
- [logging--log4j-boot](/apache/logging--log4j-boot)

## Repositories that still need work

- [logging-log4j-audit](/apache/logging-log4j-audit), [logging-log4j-audit-sample](/apache/logging-log4j-audit-sample), [logging-log4j-audit](/apache/logging-log4j-audit-site) – PMC member @rgoers objects its archival and states he will pick this up in the future
- [logging-log4j-scala](/apache/logging-log4j-scala) – Its build system is based on sbt (not Maven!) and very complicated (needs to target different Scala versions of which each require a different source code). We put significant effort to make it work with our reusable build process. There is progress, but still plenty of things to be done.
- [logging-log4j-server](/apache/logging-log4j-server) – trying to have a consensus within PMC to move the useful contents of this project to [logging-log4j-samples](/apache/logging-log4j-samples) and archive the repository
