### ISSUE TITLE
NotSerializableException when serializing Logger since 2.21.0

### ISSUE THREAD

**Issue by makkimesser** [apache/logging-log4j2#1884]
## Description

Since 2.21.0 serializing a Logger raises java.io.NotSerializableException.

Maybe this is caused by this commit (see my comment on commit): https://github.com/apache/logging-log4j2/commit/e86d28bdb927f8047b924eb459f4c63bd2e43176

## Configuration

**Version:** 2.21.0

**Operating system:** Windows-10

**JDK:** OpenJDK 1.8.0_382

## Logs

```
Exception in thread "main" java.io.NotSerializableException: java.lang.ThreadLocal
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at test.TestSerializeLogger.main(TestSerializeLogger.java:14)
```

## Reproduction

```
package test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@SuppressWarnings("javadoc")
public class TestSerializeLogger {
	public static void main(final String... args) throws IOException {
		try (ObjectOutputStream objOut = new ObjectOutputStream(new ByteArrayOutputStream())) {
			Logger logger = LogManager.getLogger("Test");
			objOut.writeObject(logger);
		}
	}
}
```

**Comment by jvz** [comment]
Alright, I've converted that test into a JUnit one here:

```java
    @Test
    void canSerializeRoundTrip() throws IOException {
        final ReusableMessageFactory factory = new ReusableMessageFactory();
        final ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        try (final ObjectOutputStream out = new ObjectOutputStream(bytes)) {
            out.writeObject(factory);
        }
        try (final ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {
            assertDoesNotThrow(in::readObject);
        }
    }
```

Should be simple enough to fix!

**Comment by vy** [comment]
@makkimesser, could you share some details about your use case, please? Why do you serialize `Logger`s?

**Comment by makkimesser** [comment]
> @makkimesser, could you share some details about your use case, please? Why do you serialize `Logger`s?

I stumbled over the issue while running our test-suite, when testing V2.21.0 and I got the mentioned NotSerializableException. There are some tests with classes containing loggers, if the logger-field is static or transient, there is no problem, but if the logger-field is non-static and non-transient the serialization method failed in V2.21.0 while it did not fail with V2.20.0.

We have such non-static and non-transient logger-fields in abstract parent classes to avoid to declare the logger in each of the child-classes. I'm not sure about the real reason of this behaviour, the code base is created before I joined my current job.

**Comment by vy** [comment]
Thanks so much for sharing these details, much appreciated.

> ... non-transient logger-fields in abstract parent classes to avoid to declare the logger in each of the child-classes.

non-`transient` fields – be it of type `Logger` or something similar – unrelated with DTO they are situated in are an accident waiting to happen. I would strongly advise you to refactor your code rather than relying on the fact that Log4j types are serializable, which won't hold anymore in Log4j 3. Is such a refactoring possible in your case? If not, would you mind sharing details?

**Comment by ppkarwasz** [comment]
@makkimesser,

The usual reason for using instance `Logger` fields on abstract classes, instead of static fields is that each subclass wants to use its own name in log messages (using the `%c` pattern, which means "logger name").

This was usually an _ersatz_ for what developers really want: the `%C` pattern, which provides the class name that generated a log statement. Traditionally the `%C` pattern is computationally expensive, but using static weaving provided by the [Log4j Transform Maven plugin](https://logging.apache.org/log4j/transform/latest/#log4j-transform-maven-plugin) you can remove the performance penalty. The plugin might be rough around the edges, but some committers already use in production.

**Comment by renoth** [comment]
The Apache Wicket Framework does serialize Pages constantly, if these Pages contain non-static Loggers (which happens sometimes) the application throws an Exception since reusablemessagefactory violates the serializable contract.

**Comment by ppkarwasz** [comment]
@renoth,

Can you check the `2.22.0-SNAPSHOT` we published on `https://repository.apache.org/snapshots`? Does it solve your problem?
