### ISSUE TITLE
notEmpty still outputs text when variable is empty

### ISSUE THREAD

**Issue by simontankersley** [apache/logging-log4j2#1922]
## Description

As per the documentation on https://logging.apache.org/log4j/2.x/manual/layouts.html, log4j2 has a *Conversion Pattern* called `notEmpty` that:

> Outputs the result of evaluating the pattern if and only if all variables in the pattern are not empty.

In version 2.20.0 of log4j2, this works as expected but in version 2.21.0 and above (at time of creating the issue) it doesn't.

Please see Reproduction section for more details.

## Configuration

**Version:** 2.21.0 and 2.21.1

**Operating system:** Mac OS 14.0

**JDK:** openjdk 17.0.5

## Logs

Please see Reproduction section for details.

## Reproduction

Please see https://github.com/simontankersley/log4j2_notEmpty_bug#readme

**Comment by vy** [comment]
@simontankersley, thanks for the report, I will check it out.

**Comment by linhartJ** [comment]
Having the same issue.

**Comment by vy** [comment]
@simontankersley, @linhartJ, problem should be fixed by dd4a88ac2e744440565e5903a9a397f5f82cacfe. Would you mind giving `2.22.0-SNAPSHOT` a try once [the associated CI run](/apache/logging-log4j2/actions/runs/6717848523) successfully finishes, please? (See [this section of the manual](https://logging.apache.org/log4j/2.x/maven-artifacts.html#snapshot-builds) on how to add snapshot repositories.)

@simontankersley, thanks so much again for the report and for taking time to create a reproduction. :heart_eyes: :bow: Feel free to comment/re-open the issue if the fix doesn't work for you.

**Comment by simontankersley** [comment]
> Would you mind giving 2.22.0-SNAPSHOT a try once [the associated CI run](https://github.com/apache/logging-log4j2/actions/runs/6717848523) successfully finishes, please?
I can confirm, things work as expected again in 2.22.0-SNAPSHOT. Thanks for turning this around so quickly!

**Comment by class101** [comment]
@vy I also confirm `2.22.0-SNAPSHOT` fixes the regression I also duplicated in #1946 

Sorry for the duplicate and thanks again guys for the fast intervention :)
