### ISSUE TITLE
Java 9 Module name wrong for slf4j 2.x

### ISSUE THREAD

**Issue by aschepp** [apache/logging-log4j2#1983]
## Description

The module log4j-to-slf4j currently uses the following module-info.class:

```
module org.apache.logging.log4j.to.slf4j {
    requires java.base;
    requires org.apache.logging.log4j;
    requires slf4j-api;

    exports org.apache.logging.slf4j;

    provides org.apache.logging.log4j.spi.Provider with
        org.apache.logging.slf4j.SLF4JProvider;
}
```

This only works with slf4j 1.x, because the module name has changed with version 2.x of slf4j, it's now "org.slf4j".

https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java9/module-info.java

## Configuration

**Version:** 2.22.0

**Operating system:** Linux/Mac

**JDK:** Java 17

## Logs

```
java.lang.module.FindException: Module slf4j-api not found, required by org.apache.logging.log4j.to.slf4j'.
```

**Comment by ppkarwasz** [comment]
@aschepp,

Thank you for noticing.

We use BND to generate both our OSGi and JPMS descriptors. The problem is caused by the multi-release nature of `slf4j-api` 2.x. Our current version of BND does not support MRJs, hence the wrong file-based name ended up in the descriptor.

Version `1.7.36` of `log4j-api` used in release 2.21.1 is not an MRJ, so you can downgrade to `log4j-to-slf4j` version 2.21.1 as a workaround.

As soon as our [CI build finishes](https://github.com/apache/logging-log4j2/actions/runs/6948583130) a new corrected `2.23.0-SNAPSHOT` version should be available. Can you check if it solves your problem? Feel free to reopen this issue if it doesn't.

**Comment by aschepp** [comment]
Downgrade to 2.21.1 worked. Thanks for the quick help.

**Comment by cowwoc** [comment]
@ppkarwasz 2.23.0-SNAPSHOT works for me. When will you cut an official release?
