### ISSUE TITLE
Revamp the `Appenders` page

### ISSUE THREAD

**Issue by vy** [apache/logging-log4j2#2528]
As agreed in [the site structure document](https://docs.google.com/document/d/10Fu7oqDzdM_D6LbexzwX9arh51Tic7AGvkWTQrL6jjQ/edit), revamp the `Appenders` page such that

- Outline:
  - What is an appender?
  - List appenders and link to the associated plugin reference page
  - Extending appenders
    - Mention about `*Manager` classes, how to handle restart
    - Explain that it is not a trivial undertaking
- Address
  - #1883 
  - #1950
- Target `2.x`, port to `main`

**Comment by ppkarwasz** [comment]
While restructuring the "Appenders" page we should explain the meaning of the `immediateFlush` option.
Looking at #2023, #2025 and other discussions, users often think that `immediateFlush` forces the OS to write the data to the underlying storage device.

That is not true, `immediateFlush` only flushes the Java buffers to the OS and due to the atomicity of the UNIX `read()/write()` calls this is usually enough for the users: if the appender logs to a pipe, the receiver should get messages up to [PIPE_BUF](https://man7.org/linux/man-pages/man7/pipe.7.html) atomically. For files and symbolic links [there is no limit](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_09_07) and operations should always be atomic.
