### ISSUE TITLE
No obvious way to report issues with the parent logging site

### ISSUE THREAD

**Issue by sebbASF** [apache/logging-log4j2#3098]
As the subject says: where should one report issues with logging.apache.org?

**Comment by ppkarwasz** [comment]
Feel free to report the problem here.

**Comment by vy** [comment]
@sebbASF, [logging.apache.org](https://logging.apache.org) has a menu item, `Support`, at the top. That page documents `User support` communication channels and several other things in the context of _support_. I presume you already figured this out yourself, but still didn't find any of the comm. channels listed there suitable to your needs. How can we adapt that page to help you?

**Comment by vy** [comment]
> The section at https://logging.apache.org/support.html#issues links to various issue trackers for sub-projcects, but does not provide info on how to report generic issues.

Got it. Updated [l.a.o/support.html](https://logging.apache.org/support.html) to guide on _"not project<sup>1</sup>-specific"_  inquiries.

<sup>1</sup> I know, Log4j is not a project, but a <b>sub</b>project. Though almost all users (including several ASF members! :facepalm:) are not aware of this fact.

> A related problem is the reporting template for issue lists such as this one is not really suited to reporting website issues. The project might wish to consider enabling issues on the logging website repo(s) and link to them from the relevant website pages

[On 2024-09-03](https://logging.apache.org/log4j/2.x/release-notes.html#_documentation), we migrated the websites of Log4j and related projects to Antora. We deliberately worked hard to ensure each Antora page is decorated with a working  `Edit` button at the top. It helped enormously – since then users contributed several website fix PRs and issues. We intend to migrate `l.a.o` to the same setup too.

I would refrain from disclosing the website repositories and documenting them. They are an internal implementation detail, they are intertwined in a sophisticated manner, and their setup is on the flux (for instance, the cited Antora change significantly disrupted that landscape, in a positive way).
